### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by SebastianKunz** [introlab/webrtc-native-build#1]
Hi,

first of all thank you for creating this project. From my experience its not very easy to build webrtc from sources, so build tools are welcomed by the community.
I ran the cmake command and get
`-- Windows build not fully supported yet.`. I was wondering if there are any plans on supporting windows in the near future?

Cheers

**Comment by doumdi** [comment]
Hello @SebastianKunz , we just added Mac build and we will work on the Windows build next. Stay tuned!
