### ISSUE TITLE
Can webrtc be compiled from source code on centos7 or centos8? 

### ISSUE THREAD

**Issue by zxx8808** [introlab/webrtc-native-build#12]
Hello, I want to know if webrtc can be compiled from source code on centos7 or centos8? There is little information available online, and compiling Webrtc from source can be complex. I want to know if it's worth attempting.
According to https://webrtc.github.io/webrtc-org/native-code/development/prerequisite-sw, seems it just support ubuntu or debian.
Thanks!

**Comment by doumdi** [comment]
@zxx8808 We did not try compiling from centos. I would stick with Google's documentation for this. However, you could try using the pre-built binaries included in this project and try using them on centos.  Good luck!
